### Assignment 2

### 5. Best problem provided by our talented students! 
### 1. When we train a neural network, we notice that the loss does not decrease in a few
       starting epochs, what’s the reason for this? What is the strategy to improve?

Please calculate X’s min-max normalizations, Z-score normalization, l2 normalization
X = np.array([[ 1., -1., 2.],
[ 2., 0., 0.],
[ 0., 1., -1.]])

<b>The reasons for this could be</b>

1. The learning is rate is low
2. Regularization parameter is high
3. Stuck at local minima

<b>Strategy to improve?</b>

1. Jitter the learning rate, i.e. change the learning rate for a few epochs
2. change weight Initialization 
3. Increase or decrease learning rate
4. Reduce Regularization

In [19]:
# Min-max Normalization

from sklearn.preprocessing import MinMaxScaler
import numpy as np
import sklearn 

X = np.array([[ 1., -1., 2.], [ 2., 0., 0.], [ 0., 1., -1.]])
scaler = MinMaxScaler()
print(scaler.fit(X))
MinMaxScaler()
print(scaler.data_max_)

# Z-score normalization
print("----------------------------")
from scipy import stats

print("Z-score")
print(stats.zscore(X))

print("----------------------------")
print("l2 normalization")
print(sklearn.preprocessing.normalize(X, norm='l2'))

MinMaxScaler(copy=True, feature_range=(0, 1))
[2. 1. 2.]
----------------------------
Z-score
[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
----------------------------
l2 normalization
[[ 0.40824829 -0.40824829  0.81649658]
 [ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]]


### 2. The problem is you are trying to train a deep learning model but only a small amount of data is available. Fortunately, there is a pre-trained neural network that was trained on a similar problem. Which one of the following methodologies is the best choice that can make use of this pre-trained network?

A. Retrain the model from scratch for the new dataset

B. Only fine-tune the last couple of layers of the pre-trained model with small learning
rate 

C. Freeze all the layers except the last, and only retrain the last layer

D. Assess on every layer how the pre-trained model performs and only select a few of them with
respect to their performances

Answer : D

### 3. Please provide at least three learning rate scheduling and briefly describe each of them.

### Answer : Common learning rate schedules are:
1. constant, 
2. time-based decay, 
3. step decay and 
4. exponential decay.

<b>Constant learning rate</b>: 
This is a default learning rate schedule in SGD optimizer in Keras. Both Momentum and decay rate are set to zero by default. It is tricky to choose the right learning rate. SGD optimizer also has an argument called nesterov which is set to false by default.

<b>Time-Based Decay</b>: 
The mathematical form of time-based decay is lr = lr0/(1+kt) where lr, k are hyperparameters and t is the iteration number When the decay argument is specified, it will decrease the learning rate from the previous epoch by the given fixed amount.

             lr *= (1. / (1. + self.decay * self.iterations))
             
             
Momentum method helps the parameter vector to build up velocity in any direction with constant gradient descent so as to prevent oscillations. A typical choice of momentum is between 0.5 to 0.9. Nesterov momentum is another type of the momentum with stronger theoretical converge guarantees for convex functions and works slightly better than standard momentum.

<b>Step Decay</b>: 
Step decay schedule drops the learning rate by a factor every few epochs. A typical way of calculating factor is to drop the learning rate by half every 10 epochs.
The mathematical form of step decay is :
                lr = lr0 * drop^floor(epoch / epochs_drop)
  
<b>Exponential Decay</b>:
Another common schedule is exponential decay. It has the mathematical form

              lr = lr0 * e^(−kt)
where lr, k are hyperparameters and t is the iteration number. Similarly, we can implement this by defining exponential decay function,but the only difference is we define a different custom decay function.

def exp_decay(epoch):
   initial_lrate = 0.1
   k = 0.1
   lrate = initial_lrate * exp(-k*t)
   return lrate
lrate = LearningRateScheduler(exp_decay)